import type { AdrianFate, EndingType, GameState, LegacyCard, SeasonOutcome, SeasonReview } from "../schemas";

export function evaluate_season_ending(state: GameState, final_equity: number): EndingType {
  const s = state as any; const ret = (final_equity / s.start_cash - 1) * 100; const comp = s.fund_stats.compliance_risk ?? 0; const lp = s.fund_stats.lp_confidence ?? 0; const morale = s.fund_stats.staff_morale ?? 0; const hidden = s.hidden_state; const reviews = s.trade_reviews ?? []; const process = reviews.length ? reviews.reduce((sum: number, review: any) => sum + review.process_score.overall_process_score, 0) / reviews.length : hidden.discipline;
  if (comp >= 75 && hidden.information_ethics < 40) return "CROSSED_THE_LINE"; if (comp >= 50 && ret > 0) return "UNDER_INVESTIGATION"; if (ret < -20 && lp < 35) return "REDEMPTION_SPIRAL";
  const team_trust = ((s.relationships?.maya_chen?.trust ?? 40) + (s.relationships?.victor_hale?.trust ?? 40)) / 2; if (ret > 15 && (morale < 35 || team_trust < 30)) return "EMPTY_OFFICE"; if ((hidden.dependency_maya ?? 0) > 75 && s.relationships?.maya_chen && (s.relationships.maya_chen.trust ?? 0) < 45) return "YOU_BUILT_A_STAR"; if (ret >= 20 && process >= 75 && comp < 35 && lp >= 60) return "THE_NEXT_KING"; if (process >= 82 && (hidden.discipline ?? 0) >= 80 && (hidden.team_building ?? 0) >= 60) return "THE_MACHINE"; if (ret >= 20 && process < 60) return "LUCKY_BASTARD"; if ((s.player_traits ?? []).includes("OVERTRADES") || hidden.ego > 70) return "THE_GAMBLER"; return "THE_SURVIVOR";
}

export function evaluate_adrian_fate(state: GameState, player_return_pct: number): AdrianFate {
  const rel = state.relationships?.adrian_cross; if (!rel) return "EQUAL_RIVAL"; if ((rel.favor ?? 0) > 30 || (rel.trust ?? 0) > 60) return player_return_pct > 15 ? "PARTNER" : "ALLY"; if ((rel.rivalry ?? 0) > 60 && player_return_pct > 20) return "DESTROYED"; if (player_return_pct > 10) return "DEFEATED"; if (player_return_pct < -10) return "DOMINANT_RIVAL"; return "EQUAL_RIVAL";
}

const TITLES: Record<EndingType, [string, string]> = {
  THE_NEXT_KING: ["新王登场 (THE NEXT KING)", "业绩、纪律与团队的全胜。你证明了在这个绞肉机里，既能赚钱也能赢得尊重"], LUCKY_BASTARD: ["幸存者偏差 (LUCKY BASTARD)", "你赚到了钱，但这只是掷硬币的结果。华尔街会拿走你的运气，只是时间问题"], THE_SURVIVOR: ["职业幸存者 (THE SURVIVOR)", "穿越算力海啸与流动性危机。活着，就是华尔街最好的履历"], EMPTY_OFFICE: ["高处不胜寒 (EMPTY OFFICE)", "净值创下新高，但你把团队当成了消耗品。这是一场孤独的胜利"], UNDER_INVESTIGATION: ["传票送达 (UNDER INVESTIGATION)", "净值很好看，但 SEC 的听证会会让你的利润和声誉一起冻结"], REDEMPTION_SPIRAL: ["流动性崩塌 (REDEMPTION SPIRAL)", "净值回撤触发了 LP 踩踏。这堂名叫流动性的课，学费是你的整个基金"], CROSSED_THE_LINE: ["越界重罪 (CROSSED THE LINE)", "信息灰产可以带来暴利，但代价是吊销牌照和司法起诉。游戏结束了"], YOU_BUILT_A_STAR: ["为他人作嫁衣 (YOU BUILT A STAR)", "你过度依赖单一明星分析师的直觉。她走了，你的底牌也就空了"], THE_MACHINE: ["机构化成功 (THE MACHINE)", "流程、纪律和量化取代了赌性。你建起了一台能长久运转的赚钱机器"], THE_GAMBLER: ["赌徒末路 (THE GAMBLER)", "大开大合的单边押注让你尝过甜头，但在波动率面前，赌徒没有好下场"],
};
const trade_label = (review: any) => `${review.contract_or_symbol} (${review.realized_pl >= 0 ? "+" : ""}${review.realized_pl.toFixed(0)} USD, ${review.return_pct >= 0 ? "+" : ""}${review.return_pct.toFixed(1)}%)`;

export function generate_season_outcome(state: GameState, final_equity: number): SeasonOutcome {
  const s = state as any; const ret = Math.round((final_equity / s.start_cash - 1) * 10000) / 100; const ending_type = evaluate_season_ending(state, final_equity); const fate = evaluate_adrian_fate(state, ret); const [ending_title, ending_subtitle] = TITLES[ending_type]; const reviews = s.trade_reviews ?? [];
  const best = reviews.length ? reviews.reduce((a: any, b: any) => a.realized_pl >= b.realized_pl ? a : b) : null; const worst = reviews.length ? reviews.reduce((a: any, b: any) => a.realized_pl <= b.realized_pl ? a : b) : null; const best_process = reviews.length ? reviews.reduce((a: any, b: any) => a.process_score.overall_process_score >= b.process_score.overall_process_score ? a : b) : null; const luckiest = reviews.length ? reviews.reduce((a: any, b: any) => a.realized_pl - a.process_score.overall_process_score * 10 >= b.realized_pl - b.process_score.overall_process_score * 10 ? a : b) : null;
  const no_trade = "DATA UNAVAILABLE (本赛季无已平仓交易)"; const trusted = Object.entries(s.relationships ?? {}).sort(([, a]: any, [, b]: any) => (b.trust ?? 0) - (a.trust ?? 0))[0]?.[0] ?? "maya_chen"; const names: Record<string, string> = { maya_chen: "Maya Chen", victor_hale: "Victor Hale", evelyn_shaw: "Evelyn Shaw", daniel_ross: "Daniel Ross", marcus_reed: "Marcus Reed", adrian_cross: "Adrian Cross", leo_park: "Leo Park" };
  const review: SeasonReview = { best_trade: best ? trade_label(best) : no_trade, worst_trade: worst ? trade_label(worst) : no_trade, luckiest_trade: luckiest ? trade_label(luckiest) : no_trade, best_process_trade: best_process ? `${best_process.contract_or_symbol} (流程评分 ${best_process.process_score.overall_process_score.toFixed(0)}/100)` : no_trade, most_trusted_character: names[trusted] ?? trusted, biggest_rival: "Adrian Cross (Northstar Capital)", compliance_incidents_count: Math.floor((s.fund_stats.compliance_risk ?? 0) / 20), lp_redemptions_count: (s.fund_stats.lp_confidence ?? 0) < 45 ? 1 : 0 };
  const legacy_card: LegacyCard = { fund_name: "Dante Capital Management", era: "2025 – 2026 (The AI Trade Era)", total_return_pct: ret, max_drawdown_pct: Math.round((s.max_drawdown_pct ?? 0) * 10) / 10, peak_aum: Math.round(Math.max(s.peak_aum ?? 0, final_equity) * 100) / 100, investment_style: "事件驱动与期权凸性策略 (Event-Driven Convexity)", risk_profile: s.hidden_state.risk_identity ?? "BALANCED", reputation_title: ending_type === "THE_NEXT_KING" || ending_type === "THE_MACHINE" ? "稳健的机构操盘手" : "追逐波动率的狂徒", team_loyalty_rating: (s.fund_stats.staff_morale ?? 0) > 65 ? "极高 (High)" : "涣散 (Low)", compliance_grade: (s.fund_stats.compliance_risk ?? 0) < 20 ? "A (Clean)" : "C- (Under Scrutiny)", legacy_quote: ret >= 0 ? "“在市场里待得够久的人，最终拼的都是风控，而非锐度。”" : "“只要流程不出错，亏损不过是付给市场的学费。”", season_summary: ending_subtitle };
  return { ending_type, ending_title, ending_subtitle, narrative_scenes: [`【Scene 1 · 收盘时刻】2026年6月30日 16:00 ET。终场钟声回荡在曼哈顿下城，Dante Capital 净值最终定格在 $${final_equity.toFixed(2)}（累计收益率: ${ret >= 0 ? "+" : ""}${ret.toFixed(2)}%）。`, "【Scene 2 · 团队命运】投研会议室内，Maya 和 Victor 在归档全年的实战复盘。他们见证了这场周期更迭，也拿到了属于他们的那份分红。", `【Scene 3 · 竞对清算】Adrian Cross 迎来了他的宿命【${fate}】。华尔街没有常胜将军，只有更迭的周期和离场的人。`, "【Scene 4 · 媒体定调】Evelyn Shaw 在专栏里写下了结论：'在这场算力与流动性的双杀中，Dante Capital 交出了一份无可辩驳的答卷。'", "【Scene 5 · 留存档案】一切尘埃落定。这不再是一场纸上谈兵的演练，这是你留在华尔街的第一份真实履历。"], adrian_fate: fate, legacy_card, season_review: review, season_2_inherited_state: { carried_aum: Math.round(final_equity * 100) / 100, reputation: s.fund_stats.reputation, team_retention: ending_type === "EMPTY_OFFICE" ? [] : ["maya_chen", "victor_hale", "leo_park"], adrian_status: fate, sec_probe_active: ending_type === "UNDER_INVESTIGATION" || ending_type === "CROSSED_THE_LINE" } };
}

