import type { GameState, LPProfile } from "../schemas";

export function get_default_lps(): LPProfile[] {
  const simulated_notice = "SIMULATED LP RELATIONSHIP -- fictional investor, not a real institution";
  return [
    { id: "lp_northlake_pension", name: "Northlake Public Employees Pension Trust", lp_type: "PENSION_FUND", allocated_capital: 25000000, target_return_pct: 10, max_tolerated_drawdown_pct: 12, liquidity_terms: "QUARTERLY_WITH_45D_NOTICE", confidence_score: 85, redemption_risk: "LOW", key_contact: "Eleanor Tremblay, Managing Director", relationship_notes: "高度关注下行波动率控制与期权尾部对冲保护纪律。", risk_appetite: "CONSERVATIVE", ethical_sensitivity: "HIGH", compliance_sensitivity: "HIGH", strategy_preference: "TAIL_HEDGE", redemption_threshold_pct: 15, capital_current: 25000000, next_review_date: "2025-04-15" },
    { id: "lp_meridian_growth_pension", name: "Meridian State Growth Pension Fund", lp_type: "PENSION_FUND", allocated_capital: 40000000, target_return_pct: 12, max_tolerated_drawdown_pct: 15, liquidity_terms: "SEMI_ANNUAL", confidence_score: 80, redemption_risk: "LOW", key_contact: "Marcus Vance, Senior Investment Officer", relationship_notes: "偏好以科技与半导体基本面增长为核心的凸性收益。", risk_appetite: "MODERATE", ethical_sensitivity: "STANDARD", compliance_sensitivity: "STANDARD", strategy_preference: "DIRECTIONAL", redemption_threshold_pct: 18, capital_current: 40000000, next_review_date: "2025-07-01" },
    { id: "lp_ivy_endowment", name: "Ivy Endowment Partners", lp_type: "ENDOWMENT", allocated_capital: 15000000, target_return_pct: 15, max_tolerated_drawdown_pct: 20, liquidity_terms: "ANNUAL_LOCKUP", confidence_score: 90, redemption_risk: "LOW", key_contact: "Dr. Charles Sterling", relationship_notes: "长期耐心资本，允许承受短期波动以换取深度 Alpha。", risk_appetite: "MODERATE", ethical_sensitivity: "STANDARD", compliance_sensitivity: "LOW", strategy_preference: "RELATIVE_VALUE", redemption_threshold_pct: 24, capital_current: 15000000, next_review_date: "2025-06-30" },
    { id: "lp_vanderbilt_park_fo", name: "Vanderbilt-Park Family Office", lp_type: "FAMILY_OFFICE", allocated_capital: 10000000, target_return_pct: 18, max_tolerated_drawdown_pct: 10, liquidity_terms: "MONTHLY_LIQUIDITY", confidence_score: 70, redemption_risk: "ELEVATED", key_contact: "Julian Park, Principal", relationship_notes: "对单周回撤极为敏感，若连续两周亏损可能发起赎回预警。", risk_appetite: "AGGRESSIVE", ethical_sensitivity: "LOW", compliance_sensitivity: "LOW", strategy_preference: "DIRECTIONAL", redemption_threshold_pct: 12, capital_current: 10000000, next_review_date: "2025-02-28" },
    { id: "lp_stonebridge_fof", name: "Stonebridge Multi-Strategy Fund of Funds", lp_type: "FUND_OF_FUNDS", allocated_capital: 30000000, target_return_pct: 14, max_tolerated_drawdown_pct: 14, liquidity_terms: "QUARTERLY", confidence_score: 78, redemption_risk: "LOW", key_contact: "Rachel Thorne, Portfolio Manager", relationship_notes: "重点审查期权交易的 Delta 中性与 Vega 敞口管理。", risk_appetite: "MODERATE", ethical_sensitivity: "STANDARD", compliance_sensitivity: "HIGH", strategy_preference: "BALANCED", redemption_threshold_pct: 17, capital_current: 30000000, next_review_date: "2025-04-01" },
    { id: "lp_founder_seed", name: "Adrian Whitfield (Founder Seed Capital)", lp_type: "FOUNDER", allocated_capital: 8000000, target_return_pct: 20, max_tolerated_drawdown_pct: 25, liquidity_terms: "NO_REDEMPTION_UNTIL_YEAR_2", confidence_score: 95, redemption_risk: "LOW", key_contact: "Adrian Whitfield, Founder", relationship_notes: "创始种子投资人，容忍度最高但对创始人个人声誉丑闻极度敏感。", risk_appetite: "AGGRESSIVE", ethical_sensitivity: "HIGH", compliance_sensitivity: "STANDARD", strategy_preference: "DIRECTIONAL", redemption_threshold_pct: 28, capital_current: 8000000, next_review_date: "2027-01-01" },
  ].map((lp) => ({ ...lp, simulated_notice }));
}

export function evaluate_lp_profiles(state: GameState, current_equity: number): LPProfile[] {
  const s = state as any; const drawdown = s.max_drawdown_pct ?? 0; const ret_pct = s.start_cash ? (current_equity - s.start_cash) / s.start_cash * 100 : 0; const profiles: LPProfile[] = s.lp_profiles?.length ? s.lp_profiles : get_default_lps();
  for (const lp of profiles) { if (!lp.capital_current || lp.capital_current <= 0) lp.capital_current = lp.allocated_capital; if (drawdown > (lp.max_tolerated_drawdown_pct ?? 0)) { lp.confidence_score = Math.max(20, 80 - (drawdown - (lp.max_tolerated_drawdown_pct ?? 0)) * 4); lp.redemption_risk = (lp.confidence_score ?? 0) < 40 ? "CRITICAL" : "ELEVATED"; } else { lp.confidence_score = Math.min(100, 80 + ret_pct * 0.5); lp.redemption_risk = "LOW"; } }
  s.lp_profiles = profiles; return profiles;
}
