import type { FlowSummary, GameState, HumanActionEvent, MarketNode, PoliticalState, PositioningSummary, RetailSentimentSnapshot, StreetConsensus } from "../schemas";

export class WhatMattersItem {
  constructor(public id: string, public headline: string, public impact: string, public affected: string, public why_it_matters: string, public character_voice = "", public source_panel = "", public source_type = "DERIVED_HEURISTIC", public confidence = "MEDIUM", public relevance_score = 0) {}
  to_dict(): Record<string, unknown> { return { id: this.id, headline: this.headline, impact: this.impact, affected: this.affected, why_it_matters: this.why_it_matters, character_voice: this.character_voice, source_panel: this.source_panel, source_type: this.source_type, confidence: this.confidence }; }
}
const SEMI_SECTORS = new Set(["SEMICONDUCTORS", "AI INFRASTRUCTURE", "GPU MAKERS", "AI DATA CENTERS", "TECHNOLOGY", "CLOUD HYPERSCALERS", "HARDWARE", "AUTO TECH"]);

export function compute_what_matters(state: GameState, node: MarketNode, pol_state?: PoliticalState | null, flow?: FlowSummary | null, positioning?: PositioningSummary | null, retail?: RetailSentimentSnapshot | null, street?: StreetConsensus | null, human_events?: HumanActionEvent[] | null): Record<string, unknown>[] {
  const candidates: WhatMattersItem[] = []; const positions = state.positions ?? []; const held = new Set(positions.map((position) => position.underlying.toUpperCase())); const has_positions = positions.length > 0; const vix = node.vix?.close ?? 16;
  if (vix >= 22) candidates.push(new WhatMattersItem("wmt_vix_elevated", `VIX ${vix.toFixed(1)} · 波动率定价失控`, "HIGH", "Growth / Nasdaq / Options Pricing", `宏观避险情绪飙升，所有期权的隐含波动率都在爆炸。${has_positions ? " 你的期权正在经受极端的 Vega 考验。" : ""}`, 'Victor: "VIX 破 22 了。别跟我扯你的长期信仰，先算算如果明天再跳空，你的账户还能不能扛住。"', "MACRO", "DERIVED_REAL_INPUTS", "HIGH", 80 + (vix - 22) * 2));
  else if (vix <= 13) candidates.push(new WhatMattersItem("wmt_vix_low", `VIX ${vix.toFixed(1)} · 极端低波陷阱`, "MEDIUM", "Options Pricing / Vol Sellers", "市场正在假装一切太平，期权权利金被压榨到极致，暴风雨前的宁静。", 'Leo: "这定价便宜得像大马路上的免费盒饭。你可以做空波动率，但最好祈祷没有黑天鹅飞出来。"', "MACRO", "DERIVED_REAL_INPUTS", "MEDIUM", 55));
  if (node.label && node.label !== "常态开盘") candidates.push(new WhatMattersItem("wmt_macro_event", node.label, "HIGH", "Broad Market", "日历上的红点已经亮起。这是重估资产的时刻，双向大幅波动的导火索已经点燃。", 'Maya: "别跟着推特上的情绪瞎叫唤。把这个事件拆开，看它到底动了多少订单、Capex 和市场预期。"', "NEWS", "REAL", "HIGH", (node.label.includes("DeepSeek") ? 90 : 70) + (has_positions ? 15 : 0)));
  for (const policy of pol_state?.active_policies ?? []) {
    if ((policy.probability_pct ?? 0) <= 30) continue;
    const sector_match = policy.sector_impact.split(",").some((sector) => SEMI_SECTORS.has(sector.trim().toUpperCase())); let score = 40 + (policy.probability_pct ?? 0) * 0.3; if (sector_match && has_positions) score += 20; if (policy.source_type === "REAL_PRIMARY") score += 10; if (score < 55) continue;
    candidates.push(new WhatMattersItem(`wmt_pol_${policy.id}`, policy.headline.replace("SIMULATED ANALYSIS: ", ""), score >= 75 ? "HIGH" : "MEDIUM", policy.sector_impact, policy.potential_transmission, "", "POLICY", policy.source_type ?? "SIMULATED", policy.source_type === "REAL_PRIMARY" ? "HIGH" : "MEDIUM", score));
  }
  if (retail) {
    const fear_greed = retail.fear_greed_index ?? 0;
    if (fear_greed >= 80) candidates.push(new WhatMattersItem("wmt_retail_euphoria", `散户狂热 (Fear & Greed ${fear_greed.toFixed(0)})`, "MEDIUM", node.underlying_bar.close.toFixed(2), "擦鞋童已经进场，末日 Call 满天飞。逼空的高潮往往离雪崩最近。", 'Victor: "不要对着狂热开空，市场能比你更久地保持非理性。检查你的风险预算，想清楚崩盘时谁跑在你前面。"', "MARKET_PULSE", "DERIVED_HEURISTIC", "MEDIUM", 65 + (has_positions ? 10 : 0)));
    else if (fear_greed <= 20) candidates.push(new WhatMattersItem("wmt_retail_panic", `散户恐慌 (Fear & Greed ${fear_greed.toFixed(0)})`, "MEDIUM", "Broad Market", "市场在无差别抛售，带血的筹码正涌入市场。流动性枯竭往往是黄金坑的开始。", 'Maya: "散户在尖叫逃命，但你要看清这是不是杀基本面。如果核心逻辑没断，这就是我们要找的击球区。"', "MARKET_PULSE", "DERIVED_HEURISTIC", "MEDIUM", 60));
  }
  if (flow) {
    if (flow.volume_shock_detected) candidates.push(new WhatMattersItem("wmt_flow_shock", `盘口异动：期权异常放量 · Relative Vol ${(flow.relative_options_vol ?? 0).toFixed(1)}x`, "HIGH", `${flow.ticker} Options`, "有人在大量扫货或清仓。成交放量本身不指明方向，每一笔买单都对应一笔卖单。由于本层级缺乏对手盘追溯能力，你无法确认这是建仓、平仓还是做市商对冲。", 'Leo: "盘口的噪音震耳欲聋。期权成交量突然放大，说明有大资金在换手，但别瞎猜方向——你连谁在买谁在卖都分不清。"', "FLOW", flow.volume_shock_source_type ?? flow.source_type ?? "SIMULATED", "LOW", 75 + (has_positions ? 15 : 0)));
    if (flow.large_sweep_count >= 5) candidates.push(new WhatMattersItem("wmt_flow_sweeps", `情景指标：Sweep 计数 ${flow.large_sweep_count}`, "MEDIUM", flow.ticker, "Sweep 指跨多个交易所快速成交的订单，通常反映对成交速度的偏好，但它既不表明下单者身份，也不表明后续方向。注意：本构建无成交回报数据源，该计数为情景常量，不是实际统计结果。", "", "FLOW", flow.large_sweep_count_source_type ?? flow.source_type ?? "SIMULATED", "LOW", 60));
  }
  if (positioning && positioning.crowdedness_score >= 75) candidates.push(new WhatMattersItem("wmt_crowding", `交易极度拥挤 · Crowdedness ${positioning.crowdedness_score.toFixed(0)}/100`, positioning.crowdedness_score >= 85 ? "HIGH" : "MEDIUM", `${positioning.ticker} / ${positioning.pain_trade_direction ?? ""}`, `当前单边押注严重超载，被套${["HIGH", "EXTREME"].includes(positioning.trapped_long_risk ?? "") ? "多头" : "空头"}随时面临被强制平仓的死亡螺旋。`, 'Leo: "整艘船的人都挤在同一侧。只要有人开始跑，Gamma 挤压就会像多米诺骨牌一样把所有人踩死在出口。"', "FLOW", positioning.source_type ?? "SIMULATED", "MEDIUM", 70 + (has_positions ? 15 : 0)));
  for (const action of human_events ?? []) if (!action.resolved) { const score = action.action_kind.startsWith("RIVAL_") ? 75 : action.action_kind.startsWith("LP_") ? 80 : action.action_kind === "REGULATORY_SUBPOENA" ? 85 : 65; candidates.push(new WhatMattersItem(`wmt_human_${action.id}`, action.headline, score >= 75 ? "HIGH" : "MEDIUM", "Fund Operations", `${action.body.slice(0, 120)}${action.body.length > 120 ? "..." : ""}`, "", "HUMAN_ACTION", "SIMULATED", "HIGH", score)); }
  if (street && ["HIGH", "EXTREME"].includes(street.rating_dispersion ?? "")) candidates.push(new WhatMattersItem("wmt_street_divergence", `华尔街评级分歧加大 · Dispersion: ${street.rating_dispersion}`, "MEDIUM", street.ticker, `卖方分析师目标价区间 $${street.low_target_price.toFixed(0)}–$${street.high_target_price.toFixed(0)}，共识尚未收敛。`, "", "WALL_STREET", street.source_type ?? "SIMULATED", "MEDIUM", 55));
  const risk_lps = (state.lp_profiles ?? []).filter((lp) => ["ELEVATED", "CRITICAL", "REDEEMING"].includes(lp.redemption_risk ?? "")); if (risk_lps.length) candidates.push(new WhatMattersItem("wmt_lp_pressure", `LP 赎回压力 · ${risk_lps.length} 家出资人风险升高`, "HIGH", "Fund AUM / LP Confidence", `${risk_lps[0].name} 等出资人赎回风险已升至 ${risk_lps[0].redemption_risk}，需关注基金运营安全。`, "", "LP_RELATIONS", "SIMULATED", "HIGH", 82));
  candidates.sort((a, b) => b.relevance_score - a.relevance_score); return candidates.slice(0, 5).map((candidate) => candidate.to_dict());
}
